[package]
name = "worksheet_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
meval = "0.2.0"
rand = "0.9.0-alpha.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
